[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=800x600
output=surface

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=16

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
core=auto
cputype=auto
cycles=auto

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c "C:\QuinteroCarrillo-post2-u8"
c:
echo DOSBox listo - Lab8 Post2
cls
